import type { NextPage } from 'next';
import Head from 'next/head';
import { styled, Button } from '@mui/material';
import styledEmo from '@emotion/styled';

const Container = styled("div")`
  min-height: 100vh;
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`

const OverstyledButton = styled(Button)`
  color: hotpink;
  background-color: paleturquoise;
`

const EmotionButton = styledEmo.button`
  color: hotpink;
  background-color: paleturquoise;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <OverstyledButton>Some Button</OverstyledButton>
      <br/>
      <EmotionButton>styled-components Button</EmotionButton>
    </Container>
  );
};

export default Home;
