import type { NextPage } from 'next';
import Head from 'next/head';
import HomeOutlined from "@mui/icons-material/HomeOutlined";
import { styled } from '@mui/material';

const Container = styled("div")`
  min-height: 100vh;
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeOutlined />
    </Container>
  );
};

export default Home;
